server {
    listen 80;
    listen [::]:80;
    server_name protector.quadravise.com;

    root /var/www/protector;
    index index.html;

    access_log /var/log/nginx/protector.access.log;
    error_log /var/log/nginx/protector.error.log;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
