name: Deploy Protector

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            set -euo pipefail
            echo "${{ secrets.VPS_PASSWORD }}" | sudo -S bash /var/www/protector-app/deploy/protector/deploy.sh
